#!/usr/bin/env bash
set -xe

rm -rf .cutekit/venv
rm -rf .cutekit/tools-ready
rm -rf sysroot/

podman run \
    --rm \
    -v "$PWD:/src" \
    -w "/src" \
    -e CUTEKIT_ALLOW_ROOT=1 \
    ubuntu:resolute \
    bash -c " \
        NO_URING=1 ./ck tools setup && \
        ./ck package --props:async=epoll --release --prefix=/opt/${COMPONENT} --sysroot=/src/sysroot ${COMPONENT} && \
        mkdir -p /src/dist && \
        cd /src/sysroot && \
        tar -czf /src/dist/${COMPONENT}_${VERSION}_generic_epoll_amd64.tar.gz *"
