#!/usr/bin/env bash
rm -rf .cutekit/venv
rm -rf .cutekit/tools-ready
rm -rf sysroot/

podman run \
    --rm \
    -v "$PWD:/src" \
    -w "/src" \
    -e CUTEKIT_ALLOW_ROOT=1 \
    ubuntu:noble \
    bash -c " \
        ./ck tools setup && \
        ./ck install --release --prefix=/opt/${COMPONENT} --sysroot=/src/sysroot ${COMPONENT} && \
        mkdir /deb && \
        mkdir /deb/DEBIAN && \
        cp -r /src/sysroot/* /deb && \
        cp -r meta/packaging/ubuntu-noble/debian/* /deb/DEBIAN && \
        mkdir -p /src/dist && \
        dpkg-deb --build /deb /src/dist/${COMPONENT}_${VERSION}_noble_amd64.deb"
