#!/usr/bin/env bash
rm -rf .cutekit/venv
rm -rf .cutekit/tools-ready
rm -rf sysroot/
podman run \
    --rm \
    -v "$PWD:/src" \
    -w "/src" \
    -e CUTEKIT_ALLOW_ROOT=1 \
    -e CUTEKIT_PYTHON=python3.11 \
    ubuntu:jammy \
    bash -c " \
        ./ck tools setup && \
        ./ck install --release --prefix=/opt/paper-muncher --sysroot=/src/sysroot paper-muncher && \
        mkdir /deb && \
        mkdir /deb/DEBIAN && \
        cp -r /src/sysroot/* /deb && \
        cp -r meta/packaging/ubuntu-jammy/debian/* /deb/DEBIAN && \
        mkdir -p /src/dist && \
        dpkg-deb --build /deb /src/dist/paper-muncher_$(CUTEKIT_VERSION)_jammy_amd64.deb"
