#!/usr/bin/env bash
set -e

rm -rf .cutekit/venv
rm -rf .cutekit/tools-ready
rm -rf sysroot/

podman run \
    --rm \
    -v "$PWD:/src" \
    -w "/src" \
    -e CUTEKIT_ALLOW_ROOT=1 \
    debian:bookworm \
    bash -c " \
        ./ck tools setup && \
        ./ck install --props:async=epoll --release --prefix=/opt/${COMPONENT} --sysroot=/src/sysroot ${COMPONENT} && \
        mkdir /deb && \
        mkdir /deb/DEBIAN && \
        cp -r /src/sysroot/* /deb && \
        cp -r meta/packaging/debian-bookworm/debian/* /deb/DEBIAN && \
        mkdir -p /src/dist && \
        dpkg-deb --build /deb /src/dist/${COMPONENT}_${VERSION}_bookworm_amd64.deb"

# Check if installing the package works
podman run --rm -v "$PWD:/src" \
    -w "/src" \
    debian:bookworm \
    bash -c " \
        apt update && \
        apt install -y /src/dist/${COMPONENT}_${VERSION}_bookworm_amd64.deb && \
        /opt/${COMPONENT}/bin/${COMPONENT} --version"
