name: Checks (Ubuntu)

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        run: ./ck tools setup && ./ck tools doctor

      - name: Build Libraries
        run: ./ck build

      - name: Test Libraries
        run: ./ck test

      - name: Run Reftests
        run: ./ck reftests run --headless
