name: Publish Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Publish Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compute Nightly Version
        id: version_env
        run: |
          PACKAGE_VERSION=$(jq -r '.version' project.json)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TAG_NAME="nightly/${PACKAGE_VERSION}-${COMMIT_HASH}"
          BUILD_VERSION="${PACKAGE_VERSION}-nightly.${COMMIT_HASH}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Setup Build Environment
        run: ./ck tools setup

      - name: Build Packages
        run: |
          meta/packaging/build
        env:
          VERSION: ${{ env.BUILD_VERSION }}
          COMPONENT: paper-muncher

      - name: Publish Release
        run: |
          gh release create "${{ env.TAG_NAME }}" dist/* --title "Nightly Build (${{ env.BUILD_VERSION }})" --notes "This is a pre-build nightly snapshot of paper-muncher. It is meant for testing purposes only and should not be used in production." --prerelease --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
