name: Rebase Stable onto Passing

on:
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase stable onto passing
        run: |
          git fetch origin stable:stable
          git fetch origin passing:passing
          git checkout stable
          git rebase "origin/passing"
